import type { PrivacyPolicyContent } from './privacy-policy-en';

export const privacyPolicyVi: PrivacyPolicyContent = {
  title: 'Chính sách bảo mật',
  breadcrumb: 'Chính sách bảo mật',
  home: 'Trang chủ',
  bodyHtml: `
    <p>Đây là Chính sách Bảo mật của Eu Yan Sang Singapore Pte Ltd (EYS) đối với Dữ liệu Khách hàng được thu thập thông qua Ứng dụng EYS, Dịch vụ Di động và Trang web. EYS thu thập, sử dụng và tiết lộ Dữ liệu Khách hàng nhằm mang đến cho bạn trải nghiệm an toàn, suôn sẻ, hiệu quả và được tùy chỉnh với EYS. Việc thu thập, sử dụng và tiết lộ Dữ liệu Khách hàng cho phép EYS cung cấp các dịch vụ và sản phẩm đáp ứng nhu cầu và yêu cầu của bạn. Chính sách Bảo mật này nêu rõ chính sách và trách nhiệm của EYS liên quan đến việc EYS thu thập, sử dụng và tiết lộ Dữ liệu Khách hàng.</p>
    <p>Bằng việc tiếp tục sử dụng các dịch vụ của EYS, bạn xác nhận rằng bạn đã đọc, hiểu và đồng ý chịu sự ràng buộc của Chính sách Bảo mật này, được sửa đổi theo từng thời điểm, đối với việc EYS thu thập, sử dụng và tiết lộ Dữ liệu Khách hàng của bạn. Vui lòng không cung cấp bất kỳ dữ liệu cá nhân nào cho chúng tôi nếu bạn không chấp nhận Chính sách này.</p>
    <p>Chính sách Bảo mật này được chia thành hai Phần – A và B:</p>
    <ul><li>Phần A: Tuyên bố chính sách bảo mật chung về Dữ liệu Khách hàng</li><li>Phần B: Tuyên bố chính sách bảo mật đối với Dữ liệu Khách hàng được thu thập thông qua các trang web của EYS (“Trang web”), cơ sở dịch vụ di động của EYS bao gồm Ứng dụng Eu Yan Sang Singapore có trên Google Playstore và Apple App Store (gọi chung là “Dịch vụ Di động”)</li></ul>
    <h2>Phần A: Tuyên bố chính sách bảo mật chung về Dữ liệu Khách hàng</h2>
    <p><strong>1. Các loại Dữ liệu Khách hàng</strong><br />Các loại Dữ liệu Khách hàng mà EYS thu thập phụ thuộc vào hoàn cảnh thu thập và bản chất của dịch vụ được yêu cầu hoặc giao dịch được thực hiện.</p>
    <p>Các nhóm Dữ liệu Khách hàng chính mà EYS thu thập tùy theo hoàn cảnh:</p>
    <ul><li>Dữ liệu Cá nhân, bao gồm:</li></ul>
    <p>(i) thông tin cá nhân bao gồm họ và tên, giới tính, ngày sinh, tình trạng hôn nhân, hộ chiếu và số nhận dạng cá nhân;</p>
    <p>(ii) thông tin liên hệ bao gồm địa chỉ, số điện thoại, địa chỉ email;</p>
    <p>(iii) thông tin thanh toán bao gồm thông tin thẻ tín dụng hoặc thẻ ghi nợ, gồm tên chủ thẻ, số thẻ, địa chỉ thanh toán và ngày hết hạn;</p>
    <p>(iv) thông tin đơn hàng bao gồm chi tiết đơn hàng, sản phẩm đã mua, số thành viên EYS và các tùy chọn dịch vụ khác;</p>
    <p>(v) thông tin kỹ thuật bao gồm địa chỉ IP, thông tin ứng dụng đã cài đặt, dữ liệu vị trí địa lý;</p>
    <ul>
      <li>Dữ liệu Thống kê bao gồm số lượng đơn hàng đã đặt, lượt truy cập Trang web và kiểu sử dụng Dịch vụ Di động của chúng tôi. Dữ liệu này chỉ nhằm mục đích phân tích và hoàn toàn trên cơ sở ẩn danh và tổng hợp. Thông tin này sẽ không được lưu vào hồ sơ khách hàng của bạn và chỉ được tổng hợp để phân tích thống kê, qua đó chúng tôi có thể hiểu rõ hơn hồ sơ khách hàng của EYS và cải thiện các dịch vụ mà EYS cung cấp.</li>
      <li>Dữ liệu Vị trí Địa lý bao gồm thông tin cho phép chúng tôi xác định vị trí của bạn, chẳng hạn khi bạn tự cung cấp thông tin vị trí hoặc cho phép thiết bị gửi cho chúng tôi thông tin vị trí chính xác. Thông tin này được sử dụng để cung cấp thông báo đẩy dựa trên vị trí khi bạn ở gần một cửa hàng và/hoặc khi bạn cố gắng tìm một cửa hàng gần mình thông qua Ứng dụng Eu Yan Sang Singapore.</li>
    </ul>
    <p>Vì mục đích của tuyên bố chính sách này, cụm từ Dữ liệu Khách hàng bao gồm Dữ liệu Cá nhân, Dữ liệu Thống kê và Dữ liệu Vị trí Địa lý.</p>
    <p>Việc cung cấp Dữ liệu Khách hàng có liên quan đến giao dịch hoặc yêu cầu dịch vụ đang được xử lý (trừ trường hợp yêu cầu dữ liệu được đánh dấu là “không bắt buộc” trong các biểu mẫu dùng để thu thập dữ liệu cá nhân) là bắt buộc để EYS thực hiện các dịch vụ cho bạn.</p>
    <p>Việc không cung cấp Dữ liệu Khách hàng đó có thể dẫn đến (i) EYS không thể cung cấp cho bạn các dịch vụ và/hoặc sản phẩm được yêu cầu; (ii) EYS không thể cập nhật cho bạn về các sản phẩm và/hoặc đợt ra mắt mới nhất của chúng tôi; và/hoặc (iii) bạn không thể tham gia các cuộc thi, chương trình khuyến mại hoặc hoạt động đổi thưởng do EYS tổ chức.</p>
    <p><strong>2. Cách Chúng tôi Thu thập Dữ liệu Cá nhân</strong><br />Chúng tôi thu thập dữ liệu cá nhân có liên quan đến mối quan hệ của chúng tôi với bạn. Chúng tôi có thể thu thập dữ liệu cá nhân của bạn trực tiếp hoặc gián tiếp qua nhiều kênh khác nhau, bao gồm khi:</p>
    <ul>
      <li>bạn truy cập Trang web, tải xuống hoặc sử dụng Dịch vụ Di động của chúng tôi (bao gồm nhưng không giới hạn ở Ứng dụng EYS);</li>
      <li>bạn sử dụng dịch vụ hoặc giao dịch với chúng tôi (hoặc bày tỏ sự quan tâm đến việc đó);</li>
      <li>bạn đăng ký làm thành viên của bất kỳ chương trình khách hàng thân thiết nào của chúng tôi, phản hồi các chương trình khuyến mại hoặc đăng ký danh sách gửi thư;</li>
      <li>bạn chia sẻ hoặc tiết lộ nhận xét, phản hồi hoặc nội dung mà bạn cung cấp qua các Trang Mạng Xã hội, qua Trang web hoặc Dịch vụ Di động hoặc cho chúng tôi (bao gồm tại các cửa hàng bán lẻ của chúng tôi);</li>
      <li>bạn cung cấp thông tin cho chúng tôi bằng cách tham gia khảo sát Cố vấn TCM Trực tuyến (có trong Ứng dụng EYS), ghi tên, email, ngày sinh, giới tính và tình trạng sức khỏe mà bạn hoặc người mà bạn đại diện có thể gặp phải;</li>
      <li>bạn đăng ký tài khoản với chúng tôi qua Trang web hoặc Dịch vụ Di động;</li>
      <li>bạn giao dịch với chúng tôi, liên hệ với chúng tôi hoặc yêu cầu chúng tôi liên hệ với bạn qua nhiều kênh liên lạc, ví dụ qua nền tảng mạng xã hội, nền tảng nhắn tin, gặp mặt trực tiếp, cuộc gọi điện thoại, email, fax và thư;</li>
      <li>hình ảnh của bạn được ghi lại qua ảnh hoặc video do chúng tôi hoặc đại diện của chúng tôi thực hiện khi bạn ở trong cơ sở của chúng tôi hoặc tham dự sự kiện do chúng tôi tổ chức;</li>
      <li>bạn tham gia các sự kiện và chương trình, cuộc thi, cuộc tranh tài hoặc trò chơi do chúng tôi tổ chức;</li>
      <li>chúng tôi tìm kiếm thông tin về bạn và nhận dữ liệu cá nhân của bạn liên quan đến mối quan hệ của bạn với chúng tôi, ví dụ nếu bạn là khách hàng, nhà đầu tư hoặc cổ đông;</li>
      <li>bạn sử dụng các dịch vụ trên Ứng dụng Eu Yan Sang Singapore cần quyền truy cập vào vị trí/dữ liệu vị trí của bạn; hoặc</li>
      <li>bạn gửi dữ liệu cá nhân cho chúng tôi vì bất kỳ lý do nào khác.</li>
    </ul>
    <p>Công nghệ định vị địa lý là các công nghệ cho phép chúng tôi xác định Quốc gia/Khu vực của bạn. Chúng tôi có thể yêu cầu bạn tự cung cấp thông tin Quốc gia/Khu vực (như mã bưu chính), hoặc cho phép thiết bị di động gửi cho chúng tôi thông tin Quốc gia/Khu vực chính xác. Ví dụ, lần đầu tải xuống và truy cập Ứng dụng EYS, bạn sẽ/có thể được yêu cầu lựa chọn cho phép hoặc không cho phép Ứng dụng truy cập Quốc gia/Khu vực của bạn và/hoặc gửi thông báo di động cho bạn. Nếu chọn “Không cho phép”, bạn đã từ chối cho Ứng dụng truy cập Quốc gia/Khu vực của mình để gửi thông báo ưu đãi dành riêng cho Quốc gia/Khu vực. Nếu chọn “OK”, Ứng dụng sẽ giao tiếp với thiết bị di động và thu thập một số dữ liệu như quy định trong Chính sách Bảo mật này. Bạn luôn có thể ngừng chia sẻ dữ liệu Quốc gia/Khu vực với Ứng dụng bằng cách thay đổi cài đặt thiết bị.</p>
    <p><strong>3. Mục đích Thu thập, Sử dụng và Tiết lộ</strong><br />EYS thu thập Dữ liệu Khách hàng để thực hiện các mục đích sau, bao gồm nhưng không giới hạn ở:</p>
    <ul>
      <li>Cung cấp dịch vụ cho bạn như xử lý giao dịch (ví dụ, mua hàng), xử lý thanh toán qua nhà cung cấp dịch vụ thanh toán, hỗ trợ kỹ thuật, hỗ trợ bạn trong giao dịch, cung cấp thông báo khuyến mại qua Dịch vụ Di động của EYS, tạo điều kiện mua hàng qua internet và đăng ký chương trình Eu Rewards của EYS;</li>
      <li>Cung cấp dịch vụ tại cửa hàng và các dịch vụ khác phù hợp nhất với sở thích và nhu cầu của bạn (mà chúng tôi có thể thu thập trong quá trình tương tác với bạn);</li>
      <li>Tiếp thị và liên lạc với bạn về các sản phẩm và dịch vụ do EYS, các đối tác dịch vụ của EYS cũng như các đại lý do EYS chỉ định cung cấp;</li>
      <li>Liên hệ với bạn để khảo sát sản phẩm hoặc mức độ hài lòng của khách hàng và nghiên cứu thị trường;</li>
      <li>Cung cấp khuyến nghị, thông tin và dịch vụ dựa trên vị trí; và</li>
      <li>An toàn, bảo mật và tuân thủ pháp luật.</li>
    </ul>
    <p>EYS cũng có thể sử dụng và tiết lộ Dữ liệu Khách hàng của bạn với và cho các bên thứ ba nhằm thực hiện các mục đích nêu trên, chẳng hạn nhà cung cấp dịch vụ thanh toán, nhà cung cấp dịch vụ vận chuyển và đối tác logistics. EYS sử dụng Stripe làm nhà cung cấp dịch vụ thanh toán bên thứ ba. Để hiểu chi tiết hơn về thực tiễn của nhà cung cấp dịch vụ thanh toán, bạn có thể tham khảo điểm 4 dưới đây và chính sách bảo mật của Stripe tại <a href="https://stripe.com/privacy">https://stripe.com/privacy</a>.</p>
    <p>EYS cũng có thể sử dụng và tiết lộ Dữ liệu Khách hàng của bạn cho những người đã được xác định hợp lệ là bạn hoặc (các) đại diện được ủy quyền của bạn theo các thủ tục bảo mật hiện hành tại thời điểm đó của chúng tôi, vì mục đích của giao dịch hoặc yêu cầu liên quan.</p>
    <p>EYS sẽ nỗ lực tối đa để bảo đảm rằng nhân viên, cán bộ, đại lý, tư vấn viên, nhà thầu và các bên thứ ba khác nêu trên có liên quan đến việc thu thập, sử dụng và tiết lộ Dữ liệu Khách hàng sẽ tuân thủ các điều khoản của Chính sách Bảo mật này.</p>
    <p>EYS có thể tiết lộ Dữ liệu Khách hàng của bạn cho các cơ quan thực thi pháp luật và chính phủ vì mục đích an ninh, hải quan. Ví dụ, trong trường hợp bạn gửi một sản phẩm của EYS cho gia đình và bạn bè ở nước ngoài.</p>
    <p>Ngoài ra, EYS có thể tiết lộ Dữ liệu Khách hàng cho các cố vấn pháp lý để xác lập, thực thi hoặc bảo vệ các quyền hợp pháp của chúng tôi, cho các cố vấn chuyên môn khác, hoặc theo cách khác được pháp luật cho phép hoặc yêu cầu. EYS cũng bảo lưu quyền chia sẻ Dữ liệu Khách hàng khi cần thiết để ngăn chặn mối đe dọa đối với tính mạng, sức khỏe hoặc an ninh của một cá nhân. Hơn nữa, EYS có thể tiết lộ Dữ liệu Khách hàng khi cần thiết để điều tra các hoạt động bị nghi ngờ là trái pháp luật, bao gồm nhưng không giới hạn ở gian lận, xâm phạm quyền sở hữu trí tuệ hoặc quyền riêng tư.</p>
    <p>EYS chỉ thu thập, sử dụng, chia sẻ và tiết lộ trên cơ sở cần thiết để cung cấp cho bạn các dịch vụ bạn đã yêu cầu. EYS sẽ không chia sẻ hoặc tiết lộ một cách không cần thiết hay bán dữ liệu cá nhân và dữ liệu nhạy cảm của người dùng cho Bên Thứ ba.</p>
    <p><strong>4. Nhà cung cấp Dịch vụ Thanh toán Bên thứ ba</strong><br />Khi truy cập nhiều sản phẩm và dịch vụ của chúng tôi bằng Trang web và Dịch vụ Di động, bạn cũng cần thanh toán cho chúng tôi để chúng tôi cung cấp sản phẩm hoặc dịch vụ được yêu cầu. EYS triển khai và sử dụng Stripe làm nhà cung cấp dịch vụ thanh toán bên thứ ba. Với tư cách nhà cung cấp dịch vụ thanh toán, Stripe thu thập thông tin phương thức thanh toán của bạn (như số thẻ tín dụng hoặc thẻ ghi nợ, hoặc thông tin tài khoản ngân hàng), số tiền mua, ngày mua và trong một số trường hợp, một số thông tin về giao dịch mua. Các phương thức thanh toán khác nhau có thể yêu cầu thu thập các nhóm thông tin khác nhau. Thông tin phương thức thanh toán mà chúng tôi thu thập sẽ phụ thuộc vào phương thức bạn chọn từ danh sách phương thức được cung cấp tại thời điểm thanh toán. Stripe cũng có thể nhận tên, email, địa chỉ thanh toán hoặc giao hàng và trong một số trường hợp, lịch sử giao dịch của bạn để xác thực bạn. Để biết thêm chi tiết, vui lòng tham khảo <a href="https://stripe.com/en-sg/privacy">Chính sách Bảo mật của Stripe.</a></p>
    <p>Nếu không muốn dữ liệu của mình được thu thập thông qua công nghệ đó, bạn có thể vô hiệu hóa hoạt động của các công nghệ này trên thiết bị (nếu có thể), hoặc không sử dụng Trang web và Dịch vụ Di động của chúng tôi.</p>
    <p><strong>5. Chuyển thông tin ra nước ngoài</strong><br />Trụ sở chính của EYS đặt tại Singapore. Dữ liệu Khách hàng có thể được truyền đến các cơ sở lưu trữ dữ liệu nơi EYS lưu giữ hồ sơ trung tâm hoặc phục vụ mục đích sao lưu. Dữ liệu Khách hàng có thể được chuyển đến các văn phòng và đại lý được chỉ định của EYS tại Singapore hoặc các quốc gia khác liên quan đến việc EYS cung cấp dịch vụ cho bạn.</p>
    <p>Khi Dữ liệu Khách hàng được chuyển ra khỏi Singapore, chúng tôi sẽ tuân thủ PDPA. Bên nhận ở nước ngoài sẽ chịu các nghĩa vụ ít nhất tương đương với PDPA.</p>
    <p><strong>6. Sự đồng ý</strong><br />Nhìn chung, trong quá trình mua hàng tại EYS hoặc khi EYS thực hiện các chức năng dịch vụ như xử lý đơn hàng, hỗ trợ đăng ký thành viên, truyền thông báo khuyến mại hoặc chấp nhận thông tin thanh toán, theo bản chất của nhiệm vụ hoặc giao dịch, Khách hàng sẽ cung cấp Dữ liệu Khách hàng cho EYS. Trong những trường hợp đó, sự đồng ý nhất thiết được ngầm hiểu từ Khách hàng rằng họ đồng ý cung cấp Dữ liệu Khách hàng để EYS cung cấp dịch vụ và/hoặc sản phẩm được yêu cầu hoặc cần thiết. Tuy nhiên, khi pháp luật yêu cầu, EYS sẽ áp dụng chính sách ‘chọn tham gia’ để có được sự đồng ý của khách hàng; khi đó, sự đồng ý rõ ràng bằng văn bản sẽ được yêu cầu khi thu thập Dữ liệu Khách hàng, ví dụ ký biểu mẫu hoặc đánh dấu ô. Khi bạn mua hàng thay mặt người khác, bạn cam kết và sẽ bảo đảm rằng cá nhân có Dữ liệu Khách hàng được cung cấp cho EYS đã cho phép việc tiết lộ, được thông báo và đồng ý với các điều khoản và điều kiện của Chính sách Bảo mật này.</p>
    <p>Bạn có thể gửi yêu cầu rút lại sự đồng ý bất kỳ lúc nào bằng cách liên hệ EYS (xem Mục 12) hoặc đăng nhập vào tài khoản Trang web hoặc Dịch vụ Di động với EYS (nếu bạn là thành viên EuRewards hoặc không phải thành viên EuRewards nhưng đã đăng ký làm người dùng Trang web hoặc Dịch vụ Di động).</p>
    <p>Dữ liệu Thống kê không được liên kết với hồ sơ khách hàng và EYS không cần xin sự đồng ý cho việc thu thập, sử dụng hoặc tiết lộ Dữ liệu Thống kê. Để biết thêm thông tin về việc thu thập và sử dụng Dữ liệu Khách hàng có được từ Trang web và qua Dịch vụ Di động, vui lòng tham khảo Phần B.</p>
    <p><strong>7. Quyền truy cập</strong><br />Theo yêu cầu bằng văn bản của bạn gửi Cán bộ Bảo vệ Dữ liệu Cá nhân (xem Mục 12), EYS sẽ cho phép bạn truy cập Dữ liệu Cá nhân được lưu trữ. Khi pháp luật cho phép, EYS bảo lưu quyền thu một khoản phí hành chính hợp lý cho dịch vụ này. Khi pháp luật cho phép, EYS bảo lưu quyền từ chối cho bạn truy cập Dữ liệu Cá nhân và có thể đưa ra lời giải thích.</p>
    <p><strong>8. Lưu giữ</strong><br />EYS sẽ lưu giữ Dữ liệu Khách hàng trong thời gian cần thiết để thực hiện mục đích thu thập, các mục đích pháp lý hoặc kinh doanh của EYS, hoặc theo yêu cầu của luật pháp liên quan.<br />Khi tiêu hủy Dữ liệu Khách hàng, chúng tôi sẽ thực hiện các biện pháp hợp lý về mặt thương mại và khả thi về mặt kỹ thuật để khiến thông tin cá nhân không thể khôi phục hoặc tái tạo theo luật hiện hành.</p>
    <p><strong>9. Tính chính xác</strong><br />EYS cần sự hỗ trợ của bạn để bảo đảm Dữ liệu Cá nhân của bạn là hiện hành, đầy đủ và chính xác. Vì vậy, vui lòng thông báo cho EYS về những thay đổi đối với Dữ liệu Cá nhân bằng cách liên hệ EYS và gửi thông tin cập nhật cho EYS bằng văn bản (xem Mục 12).</p>
    <p>EYS cũng có thể yêu cầu bạn cập nhật Dữ liệu Cá nhân theo từng thời điểm. Như nêu chi tiết tại Mục 3 trên đây trong tiểu mục “Sử dụng và Tiết lộ”, thông tin đơn hàng của bạn có thể được tiết lộ cho cơ quan hải quan và nhập cư thích hợp (đối với giao dịch mua ở nước ngoài) theo yêu cầu pháp luật. Vì vậy, điều quan trọng là phải bảo đảm Dữ liệu Cá nhân trong thông tin đơn hàng của bạn là hiện hành, đầy đủ và chính xác.</p>
    <p><strong>10. Biện pháp bảo vệ an ninh</strong><br />EYS rất coi trọng an ninh và việc bảo vệ Dữ liệu Khách hàng. Vì vậy, EYS thực hiện các biện pháp an ninh hợp lý để bảo vệ Dữ liệu Khách hàng khỏi bị mất hoặc đánh cắp cũng như truy cập trái phép và tiết lộ không chính đáng.</p>
    <p>Ví dụ về biện pháp bảo vệ theo thủ tục, EYS đã triển khai nhiều thủ tục xác thực nội bộ và với các nhà cung cấp dịch vụ bên ngoài; các thủ tục này có thể bao gồm việc EYS yêu cầu bạn cung cấp nhiều thông tin cá nhân để xác minh danh tính của bạn (hoặc đại lý được bạn ủy quyền hợp lệ) trước khi EYS xử lý yêu cầu về một dịch vụ, sản phẩm hoặc giao dịch cụ thể.</p>
    <p>Ví dụ về biện pháp bảo vệ kỹ thuật bao gồm mã hóa, “tường lửa” và Secure Socket Layer (SSL). Chi tiết thêm về các biện pháp kỹ thuật này đối với Dữ liệu Khách hàng được thu thập qua Trang web và Dịch vụ Di động của EYS được nêu tại Phần B dưới đây.</p>
    <p>Khách hàng có trách nhiệm thận trọng và bảo đảm tính bảo mật và chính xác liên tục của Dữ liệu Khách hàng. EYS sẽ không chịu trách nhiệm đối với bất kỳ hành vi sử dụng sai mục đích và/hoặc gian lận kéo theo nào. Nếu có bất kỳ quan ngại nào về an ninh, bạn nên liên hệ EYS (xem Mục 12).</p>
    <p><strong>11. Cập nhật chính sách bảo mật</strong><br />EYS sẽ sửa đổi Chính sách Bảo mật này theo từng thời điểm và các phiên bản cập nhật sẽ được đăng trên Trang web và Dịch vụ Di động của EYS và được đóng dấu ngày để bạn biết Chính sách Bảo mật được cập nhật lần cuối khi nào. Tùy thuộc luật hiện hành, bản tiếng Anh của Chính sách Bảo mật này sẽ được ưu tiên áp dụng so với mọi phiên bản bằng ngôn ngữ khác. Trong trường hợp có bất kỳ sự không nhất quán nào trong cách giải thích giữa bản tiếng Anh và bất kỳ bản dịch nào của Chính sách Bảo mật, tuyên bố Chính sách Bảo mật bằng tiếng Anh này sẽ được ưu tiên áp dụng.</p>
    <p><strong>12. [Chỉ dành cho Người dùng iOS] Đóng Tài khoản Trực tuyến</strong><br />Tài khoản Trực tuyến là tài khoản do người dùng đăng ký để bạn mua sản phẩm EYS trực tuyến.</p>
    <p>Bất kỳ lúc nào, bạn có thể gửi yêu cầu đóng Tài khoản Trực tuyến. Sau khi gửi yêu cầu qua Ứng dụng EYS iOS, chúng tôi sẽ xử lý yêu cầu và xóa toàn bộ Dữ liệu Cá nhân khỏi hồ sơ, trừ khi áp dụng ngoại lệ.</p>
    <p>Các ngoại lệ đó bao gồm:</p>
    <ul><li>Dữ liệu Cá nhân được sử dụng cho chương trình EuRewards.</li><li>để hoàn tất giao dịch, cung cấp hàng hóa hoặc dịch vụ mà bạn yêu cầu, hoặc thực hiện hợp đồng với bạn theo cách khác.</li><li>phát hiện sự cố an ninh, bảo vệ chống lại hoạt động độc hại, lừa dối, gian lận hoặc bất hợp pháp, hoặc truy tố những người chịu trách nhiệm về các hoạt động đó.</li><li>gỡ lỗi sản phẩm để xác định và sửa chữa lỗi làm suy giảm chức năng dự kiến hiện có.</li><li>tuân thủ nghĩa vụ pháp lý.</li></ul>
    <p>Bạn cần lưu ý rằng việc đóng Tài khoản Trực tuyến là vĩnh viễn và không thể đảo ngược.</p>
    <p>Chương trình EuRewards là một hệ thống thành viên riêng biệt và không bị ảnh hưởng bởi việc đóng Tài khoản Trực tuyến.</p>
    <p><strong>13. Liên hệ với chúng tôi / Thông tin Liên hệ của Cán bộ Bảo vệ Dữ liệu Cá nhân</strong><br />Nếu bạn có nhận xét, câu hỏi hoặc khiếu nại hay yêu cầu liên quan đến tuyên bố Chính sách Bảo mật này hoặc cách EYS xử lý dữ liệu cá nhân, vui lòng liên hệ EYS bằng văn bản theo địa chỉ dưới đây và ghi tham chiếu ‘Privacy Policy’:</p>
    <p><br /><strong>Personal Data Protection Officer</strong></p>
    <p><strong>Eu Yan Sang Singapore Pte Ltd<br />Eu Yan Sang Centre<br />21 Tai Seng Drive<br />Singapore 535223</strong><br />Email: <a href="mailto:pdpo-eyss@euyansang.com">pdpo-eyss@euyansang.com</a> ghi tham chiếu: Privacy Policy.</p>
    <p>Ngoài ra, đối với các câu hỏi riêng về Eu Rewards, bạn có thể liên hệ:</p>
    <p>Eu Rewards Membership Services<br />Eu Yan Sang Centre<br />21 Tai Seng Drive<br />Singapore 535223<br />Email: <a href="mailto:eurewards.sg@euyansang.com">eurewards.sg@euyansang.com</a></p>
    <p>&nbsp;</p>
    <h2>Phần B: Tuyên bố chính sách bảo mật đối với Dữ liệu Khách hàng được thu thập qua các trang web và cơ sở dịch vụ di động của chúng tôi</h2>
    <p><strong>1.1. Cookie</strong><br />Hầu hết các trang web và dịch vụ di động như của chúng tôi sử dụng cookie để nâng cao trải nghiệm trực tuyến. Cookie là một chuỗi thông tin nhỏ mà trang web hoặc dịch vụ di động bạn truy cập chuyển đến máy tính nhằm mục đích nhận dạng. Cookie có thể được dùng để theo dõi hoạt động của bạn trên Trang web và Dịch vụ Di động; thông tin đó giúp chúng tôi hiểu sở thích của bạn và cải thiện trải nghiệm Trang web và Dịch vụ Di động. Cookie cũng được dùng để ghi nhớ, chẳng hạn, tên người dùng và mật khẩu.</p>
    <p>Bạn có thể tắt tất cả cookie nếu không muốn nhận chúng. Bạn cũng có thể cài đặt để máy tính hoặc thiết bị di động cảnh báo mỗi khi cookie được sử dụng. Đối với cả hai lựa chọn, bạn phải điều chỉnh cài đặt trình duyệt (như internet explorer). Cũng có các sản phẩm phần mềm có thể quản lý cookie cho bạn. Tuy nhiên, xin lưu ý rằng khi cài đặt máy tính từ chối cookie, chức năng của Trang web và Dịch vụ Di động có thể bị hạn chế và khi đó bạn có thể không truy cập được một số tính năng.</p>
    <p><strong>1.2. Công cụ Phân tích</strong><br />Chúng tôi sử dụng các công cụ phân tích của bên thứ ba cho mục đích phân tích dữ liệu. Các công cụ này chỉ phân tích và tổng hợp dữ liệu đã được ẩn danh. Chúng bao gồm Google Analytics, một dịch vụ phân tích web do Google cung cấp. Google sử dụng dữ liệu được thu thập để theo dõi và kiểm tra việc sử dụng www.EuYanSang.com.sg, lập báo cáo về hoạt động và chia sẻ các báo cáo đó với các dịch vụ khác của Google. Google có thể sử dụng dữ liệu được thu thập để đặt quảng cáo của mạng quảng cáo riêng trong ngữ cảnh và cá nhân hóa chúng. Để biết thêm chi tiết, vui lòng tham khảo <a href="https://policies.google.com/privacy?hl=en">Chính sách Bảo mật của Google</a>.</p>
    <p><strong>2. Biện pháp bảo vệ an ninh</strong><br />EYS rất coi trọng việc bảo vệ Dữ liệu Khách hàng được thu thập trên các trang web của EYS và qua Dịch vụ Di động. Toàn bộ Dữ liệu Khách hàng được thu thập qua các trang web của EYS, ví dụ <a href="https://www.euyansang.com.sg/">https://www.EuYanSang.com.sg</a>, và qua Dịch vụ Di động của EYS đều được bảo vệ bằng máy chủ bảo mật. Ngoài ra, SSL (Secure Socket Layer) bảo vệ việc truyền dữ liệu từ internet đến hệ thống của chúng tôi.</p>
    <ul><li>Ví dụ, khi bạn truyền thông tin nhạy cảm như chi tiết thẻ tín dụng qua Trang web hoặc Dịch vụ Di động của EYS, thông tin đó sẽ được mã hóa trước khi gửi qua internet.</li><li>Để tăng cường hơn nữa tính toàn vẹn của các giao dịch internet trên Trang web và Dịch vụ Di động, EYS cũng sử dụng các chương trình phần mềm liên quan để giám sát lưu lượng mạng nhằm xác định các nỗ lực trái phép để tải lên hoặc thay đổi Dữ liệu Khách hàng, thực hiện hoạt động gian lận hoặc bất hợp pháp hoặc gây thiệt hại theo cách khác. Nếu việc giám sát cho thấy bằng chứng về hành vi lạm dụng hoặc hoạt động tội phạm có thể xảy ra, bằng chứng đó có thể được cung cấp cho cơ quan thực thi pháp luật thích hợp mà không thông báo cho bạn.</li><li>Để truy cập an toàn các dịch vụ trực tuyến phát sinh từ việc sử dụng Dịch vụ Di động của EYS và tài khoản EuRewards, bạn cần đăng ký tài khoản người dùng. User Name/User ID và Password/Pin là duy nhất, mang tính cá nhân và bạn không nên chia sẻ với bất kỳ ai. Bạn cũng phải luôn ‘đăng xuất’ sau khi kết thúc phiên trên Trang web và Dịch vụ Di động, đồng thời thực hiện các biện pháp phòng ngừa được khuyến nghị để bảo đảm sử dụng Trang web và Dịch vụ Di động của EYS an toàn và bảo mật.</li><li>Nếu phát hiện bất thường, bạn phải thông báo ngay cho EYS.</li></ul>
    <p><strong>3. Dữ liệu dòng nhấp chuột</strong><br />Để cải thiện trải nghiệm trực tuyến, EYS có thể theo dõi hành vi trực tuyến hoặc dữ liệu dòng nhấp chuột nhằm cải thiện việc bạn sử dụng các trang web và theo dõi lượt giới thiệu từ trang web hoặc dịch vụ di động khác. Dữ liệu đó sẽ không được lưu vào hồ sơ khách hàng và chỉ được tổng hợp để phân tích thống kê.</p>
    <p><strong>4. Liên kết đến các trang web khác</strong><br />EYS cung cấp liên kết đến các trang web khác để thuận tiện và cung cấp thông tin cho bạn. Bạn tự chịu rủi ro khi truy cập các trang web này và EYS không chịu trách nhiệm về chúng. Mặc dù EYS sẽ bảo vệ Dữ liệu Khách hàng trên các Trang web của EYS, EYS không thể kiểm soát hoặc chịu trách nhiệm về chính sách của các trang khác mà chúng tôi có thể liên kết đến, hoặc việc sử dụng bất kỳ Dữ liệu Khách hàng nào mà bạn có thể chia sẻ với họ. Xin lưu ý rằng Chính sách Bảo mật của EYS không áp dụng cho các trang web khác này và EYS khuyến nghị bạn tìm hiểu các chính sách cụ thể tương ứng của họ.</p>
    <p><strong>5. Người chưa thành niên</strong><br />EYS không thể phân biệt độ tuổi của những người truy cập và sử dụng Trang web và Dịch vụ Di động. Nếu người chưa thành niên (theo luật hiện hành) đã cung cấp Dữ liệu Khách hàng cho EYS mà không có sự đồng ý của cha mẹ hoặc người giám hộ, cha mẹ hoặc người giám hộ nên liên hệ EYS để xóa Dữ liệu Khách hàng liên quan và hủy đăng ký của người chưa thành niên.</p>
    <p>Trang web nơi Chính sách và Chính sách sửa đổi sẽ được cung cấp<br /><a href="https://www.euyansang.com.sg/en/privacy-policy/privacy-policy.html">https://www.euyansang.com.sg/en/privacy-policy/privacy-policy.html</a></p>
    <p>Cập nhật lần cuối vào ngày 18 tháng 7 năm 2022</p>
  `,
};
